import { supabase } from '../lib/supabase';
import type { AdminSupportTicket, SupportMessage, SupportSummary, SupportTicket } from '../types/support';

const errorIfMissing = () => new Error('إعداد Supabase غير مكتمل.');
const client = () => { if (!supabase) throw errorIfMissing(); return supabase; };
const rows = <T>(data: unknown): T[] => (Array.isArray(data) ? data : []) as T[];

export async function createSupportTicket(subject:string, category:string, message:string) { try { const {data,error}=await client().rpc('create_support_ticket',{p_subject:subject,p_category:category,p_message:message}); return {ticket:data as SupportTicket|null,error}; } catch(error){return {ticket:null,error:error instanceof Error?error:new Error('تعذر إنشاء التذكرة.')}} }
export async function getMySupportTickets(page=1,pageSize=12) { try { const {data,error}=await client().rpc('get_my_support_tickets',{p_page:page,p_page_size:pageSize}); const list=rows<SupportTicket & {total_count?:number}>(data); return {tickets:list,totalCount:list[0]?.total_count??0,error}; } catch(error){return {tickets:[],totalCount:0,error:error instanceof Error?error:new Error('تعذر تحميل التذاكر.')}} }
export async function getMySupportTicket(id:string) { try { const {data,error}=await client().rpc('get_my_support_ticket',{p_ticket_id:id}); return {ticket:rows<SupportTicket>(data)[0]??null,error}; } catch(error){return {ticket:null,error:error instanceof Error?error:new Error('تعذر تحميل التذكرة.')}} }
export async function getMySupportMessages(id:string) { try { const {data,error}=await client().rpc('get_my_support_messages',{p_ticket_id:id}); return {messages:rows<SupportMessage>(data),error}; } catch(error){return {messages:[],error:error instanceof Error?error:new Error('تعذر تحميل المحادثة.')}} }
export async function addSupportMessage(id:string,message:string) { try { const {data,error}=await client().rpc('add_support_message',{p_ticket_id:id,p_message:message}); return {message:data as SupportMessage|null,error}; } catch(error){return {message:null,error:error instanceof Error?error:new Error('تعذر إرسال الرد.')}} }
export async function reopenSupportTicket(id:string) { try { const {data,error}=await client().rpc('reopen_support_ticket',{p_ticket_id:id}); return {ticket:data as SupportTicket|null,error}; } catch(error){return {ticket:null,error:error instanceof Error?error:new Error('تعذر إعادة فتح التذكرة.')}} }
export async function getAdminSupportTickets(filters:{status?:string;priority?:string;category?:string;search?:string},page=1,pageSize=12) { try { const {data,error}=await client().rpc('get_admin_support_tickets',{p_status:filters.status||null,p_priority:filters.priority||null,p_category:filters.category||null,p_search:filters.search||null,p_page:page,p_page_size:pageSize}); const list=rows<AdminSupportTicket & {total_count?:number}>(data); return {tickets:list,totalCount:list[0]?.total_count??0,error}; } catch(error){return {tickets:[],totalCount:0,error:error instanceof Error?error:new Error('تعذر تحميل تذاكر الدعم.')}} }
export async function getAdminSupportTicket(id:string) { try { const {data,error}=await client().rpc('get_admin_support_ticket',{p_ticket_id:id}); return {ticket:rows<AdminSupportTicket>(data)[0]??null,error}; } catch(error){return {ticket:null,error:error instanceof Error?error:new Error('تعذر تحميل التذكرة.')}} }
export async function getAdminSupportMessages(id:string) { try { const {data,error}=await client().rpc('get_admin_support_messages',{p_ticket_id:id}); return {messages:rows<SupportMessage>(data),error}; } catch(error){return {messages:[],error:error instanceof Error?error:new Error('تعذر تحميل المحادثة.')}} }
export async function adminReplySupportTicket(id:string,message:string) { try { const {data,error}=await client().rpc('admin_reply_support_ticket',{p_ticket_id:id,p_message:message}); return {message:data as SupportMessage|null,error}; } catch(error){return {message:null,error:error instanceof Error?error:new Error('تعذر إرسال الرد.')}} }
export async function adminUpdateSupportTicket(id:string,status:string,priority:string) { try { const {data,error}=await client().rpc('admin_update_support_ticket',{p_ticket_id:id,p_status:status,p_priority:priority}); return {ticket:data as SupportTicket|null,error}; } catch(error){return {ticket:null,error:error instanceof Error?error:new Error('تعذر تحديث التذكرة.')}} }
export async function getAdminSupportSummary() { try { const {data,error}=await client().rpc('get_admin_support_summary'); return {summary:rows<SupportSummary>(data)[0]??null,error}; } catch(error){return {summary:null,error:error instanceof Error?error:new Error('تعذر تحميل إحصائيات الدعم.')}} }
