import { useEffect,useState } from 'react';
import AdminRoute from '../components/AdminRoute';
import { getAdminSupportTickets } from '../services/supportService';
import type { AdminSupportTicket,SupportCategory,SupportPriority,SupportStatus } from '../types/support';
import { AdminPage } from './AdminDashboardPage';
const cats:[SupportCategory,string][]=[['account','الحساب'],['request','الطلبات'],['offer','العروض'],['supplier','الموردون'],['verification','التوثيق'],['subscription','PRO / الاشتراك'],['technical','مشكلة تقنية'],['other','أخرى']];
const labels={open:'مفتوحة',in_progress:'قيد المعالجة',waiting_user:'بانتظار المستخدم',resolved:'تم الحل',closed:'مغلقة'} as Record<string,string>;
const pr={low:'منخفضة',normal:'عادية',high:'عالية',urgent:'عاجلة'} as Record<string,string>;
const dt=(v:string)=>new Intl.DateTimeFormat('ar-SY',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v));
export default function AdminSupportPage(){return <AdminRoute><Content/></AdminRoute>}
function Content(){const [tickets,setTickets]=useState<AdminSupportTicket[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[error,setError]=useState('');const [status,setStatus]=useState(''),[priority,setPriority]=useState(''),[category,setCategory]=useState(''),[search,setSearch]=useState('');
 const load=async(p=page)=>{setLoading(true);setError('');const r=await getAdminSupportTickets({status,priority,category,search},p,12);setTickets(r.tickets);setTotal(r.totalCount);if(r.error)setError(r.error.message || 'تعذر تحميل تذاكر الدعم.');setLoading(false)};useEffect(()=>{void load(1)},[status,priority,category]);
 return <AdminPage><div className="mb-7 flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-black text-slate-400">إدارة المنصة</p><h1 className="mt-1 text-3xl font-black">الدعم والتذاكر</h1><p className="mt-2 text-sm text-slate-500">إدارة التذاكر والردود والحالات والأولويات.</p></div><button onClick={()=>void load(page)} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold">تحديث</button></div>
 <div className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 md:grid-cols-5"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void load(1)} placeholder="بحث بالموضوع أو اسم المستخدم" className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none"/><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm"><option value="">كل الحالات</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm"><option value="">كل الأولويات</option>{Object.entries(pr).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm"><option value="">كل التصنيفات</option>{cats.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button onClick={()=>{setPage(1);void load(1)}} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-black text-white">بحث</button></div>
 {error&&<div className="mt-5 rounded-xl bg-rose-50 px-4 py-3 text-sm font-bold text-rose-700">{error}</div>}
 <div className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white">{loading?<div className="p-12 text-center font-bold text-slate-500">جارٍ التحميل...</div>:tickets.length===0?<div className="p-12 text-center"><h2 className="font-black">لا توجد تذاكر مطابقة</h2><p className="mt-2 text-sm text-slate-500">غيّر الفلاتر أو أنشئ تذكرة جديدة.</p></div>:<div className="divide-y divide-slate-100">{tickets.map(t=><a href={`/admin/support/${t.id}`} key={t.id} className="block p-5 hover:bg-slate-50"><div className="grid gap-3 lg:grid-cols-[1.7fr_1fr_.8fr_.8fr_1fr]"><div><h3 className="font-black">{t.subject}</h3><p className="mt-1 text-xs font-bold text-slate-400">{t.user_name||'مستخدم'} · {t.user_email||''}</p></div><span className="text-sm font-bold text-slate-600">{cats.find(c=>c[0]===t.category)?.[1]||t.category}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-center text-xs font-black">{labels[t.status]}</span><span className={`rounded-full px-2.5 py-1 text-center text-xs font-black ${t.priority==='urgent'?'bg-rose-50 text-rose-700':'bg-amber-50 text-amber-700'}`}>{pr[t.priority]}</span><span className="text-xs font-bold text-slate-400">{dt(t.updated_at)}</span></div></a>)}</div>}</div>
 {total>12&&<div className="mt-5 flex items-center justify-between rounded-xl border border-slate-200 bg-white p-3"><button disabled={page===1} onClick={()=>{setPage(p=>p-1);void load(page-1)}} className="rounded-lg border px-3 py-2 text-sm font-bold disabled:opacity-40">السابق</button><span className="text-sm font-black">صفحة {page} / {Math.ceil(total/12)}</span><button disabled={page>=Math.ceil(total/12)} onClick={()=>{setPage(p=>p+1);void load(page+1)}} className="rounded-lg border px-3 py-2 text-sm font-bold disabled:opacity-40">التالي</button></div>}</AdminPage>}
