import { useEffect, useMemo, useState, type ReactNode } from "react";
import AdminRoute from "../components/AdminRoute";
import { AdminPage } from "./AdminDashboardPage";
import { getAdminActivity, getAdminActiveSuppliers, getAdminOfferAnalytics, getAdminProAnalytics, getAdminReportSummary, getAdminRequestFunnel, getAdminStatusDistribution, getAdminTopCategories, getAdminTopCities, getAdminVerificationAnalytics } from "../services/adminService";
import type { ActivityPoint, ActiveSupplier, AdminReportSummary, OfferAnalytics, ProAnalytics, ReportPeriod, RequestFunnel, StatusPoint, TopCategory, TopCity, VerificationAnalytics } from "../types/adminReports";

const nf = new Intl.NumberFormat("ar-SY");
function localIsoDate(d: Date) { const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0"); return `${y}-${m}-${day}`; }
function periodFromDates(from:string|null,to:string|null,label:string):ReportPeriod { if(!from||!to) return {from:null,toExclusive:null,label}; const start=new Date(`${from}T00:00:00`); const end=new Date(`${to}T00:00:00`); end.setDate(end.getDate()+1); return {from:start.toISOString(),toExclusive:end.toISOString(),label}; }
function quickPeriod(key:string):ReportPeriod { const now=new Date(); const end=localIsoDate(now); if(key==='all') return periodFromDates(null,null,'كل الفترة'); if(key==='month'){const d=new Date(now.getFullYear(),now.getMonth(),1);return periodFromDates(localIsoDate(d),end,'هذا الشهر');} if(key==='year'){const d=new Date(now.getFullYear(),0,1);return periodFromDates(localIsoDate(d),end,'هذا العام');} const days=Number(key); const d=new Date(now); d.setDate(d.getDate()-days+1); return periodFromDates(localIsoDate(d),end,`آخر ${days} يومًا`); }
function defaultPeriod(){return quickPeriod('30');}

export default function AdminReportsPage(){ return <AdminRoute><ReportsContent/></AdminRoute>; }
function ReportsContent(){
 const def=defaultPeriod(); const [period,setPeriod]=useState(def); const [from,setFrom]=useState(localIsoDate(new Date(Date.now()-29*86400000))); const [to,setTo]=useState(localIsoDate(new Date()));
 const [loading,setLoading]=useState(true),[error,setError]=useState("");
 const [summary,setSummary]=useState<AdminReportSummary|null>(null),[funnel,setFunnel]=useState<RequestFunnel|null>(null),[offers,setOffers]=useState<OfferAnalytics|null>(null),[cats,setCats]=useState<TopCategory[]>([]),[cities,setCities]=useState<TopCity[]>([]),[suppliers,setSuppliers]=useState<ActiveSupplier[]>([]),[activity,setActivity]=useState<ActivityPoint[]>([]),[statuses,setStatuses]=useState<StatusPoint[]>([]),[pro,setPro]=useState<ProAnalytics|null>(null),[verification,setVerification]=useState<VerificationAnalytics|null>(null);
 const [catPage,setCatPage]=useState(1),[cityPage,setCityPage]=useState(1),[supplierPage,setSupplierPage]=useState(1); const [catNext,setCatNext]=useState(false),[cityNext,setCityNext]=useState(false),[supplierNext,setSupplierNext]=useState(false);
 const granularity=useMemo(()=> period.from&&period.toExclusive && (new Date(period.toExclusive).getTime()-new Date(period.from).getTime())/86400000<=45 ? 'day':'month',[period]);
 async function load(p=period){ setLoading(true);setError(""); const [a,b,c,d,e,f,g,h,i,j]=await Promise.all([getAdminReportSummary(p.from,p.toExclusive),getAdminRequestFunnel(p.from,p.toExclusive),getAdminOfferAnalytics(p.from,p.toExclusive),getAdminTopCategories(p.from,p.toExclusive,catPage),getAdminTopCities(p.from,p.toExclusive,cityPage),getAdminActiveSuppliers(p.from,p.toExclusive,supplierPage),getAdminActivity(p.from,p.toExclusive,granularity),getAdminStatusDistribution(p.from,p.toExclusive),getAdminProAnalytics(p.from,p.toExclusive),getAdminVerificationAnalytics(p.from,p.toExclusive)]); const rs=[a,b,c,d,e,f,g,h,i,j]; if(rs.some(x=>x.error)) setError("تعذر تحميل بعض بيانات التقارير. تحقق من اتصال Supabase وصلاحيات الإدارة."); setSummary(a.data);setFunnel(b.data);setOffers(c.data);setCats(d.data);setCatNext(d.hasNextPage);setCities(e.data);setCityNext(e.hasNextPage);setSuppliers(f.data);setSupplierNext(f.hasNextPage);setActivity(g.data);setStatuses(h.data);setPro(i.data);setVerification(j.data);setLoading(false); }
 useEffect(()=>{void load()},[period,catPage,cityPage,supplierPage,granularity]);
 function applyDates(){ if(!from||!to||new Date(`${from}T00:00:00`)>new Date(`${to}T00:00:00`)){setError("تأكد من أن تاريخ البداية لا يتجاوز تاريخ النهاية.");return;} setCatPage(1);setCityPage(1);setSupplierPage(1);setPeriod(periodFromDates(from,to,`من ${from} إلى ${to}`)); }
 const empty=!loading && (!summary || !funnel || !offers || !pro || !verification) && !error;
 return <AdminPage><div className="mb-7"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-black text-slate-400">تحليل المنصة</p><h1 className="mt-1 text-3xl font-black">التقارير والإحصائيات</h1><p className="mt-2 text-sm text-slate-500">بيانات محسوبة مباشرة في PostgreSQL للفترة: {period.label}.</p></div><button disabled={loading} onClick={()=>void load()} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold hover:bg-slate-50 disabled:opacity-50">{loading?'جارٍ التحديث...':'تحديث'}</button></div></div>
 <section className="mb-7 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-wrap gap-2 mb-4">{[['7','آخر 7 أيام'],['30','آخر 30 يومًا'],['90','آخر 90 يومًا'],['month','هذا الشهر'],['year','هذا العام'],['all','كل الفترة']].map(([k,l])=><button key={k} onClick={()=>{const p=quickPeriod(k);setPeriod(p);if(p.from){setFrom(localIsoDate(new Date(p.from)));const x=new Date(p.toExclusive!);x.setDate(x.getDate()-1);setTo(localIsoDate(x));}}} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-black hover:bg-slate-50">{l}</button>)}</div><div className="grid gap-3 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><label className="text-sm font-bold">من<input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2"/></label><label className="text-sm font-bold">إلى<input type="date" value={to} onChange={e=>setTo(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2"/></label><button onClick={applyDates} className="rounded-xl bg-slate-950 px-5 py-2.5 text-sm font-black text-white">تطبيق الفترة</button></div></section>
 {error&&<div className="mb-6 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-bold text-rose-700">{error}</div>}
 {loading?<Loading/>:error?<div/>:empty?<div className="rounded-2xl border border-slate-200 bg-white p-12 text-center font-bold text-slate-500">لا توجد بيانات ضمن الفترة المحددة.</div>:<>
 <Section title="المؤشرات الرئيسية"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['إجمالي المستخدمين',summary!.totalUsers],['مستخدمون جدد',summary!.newUsers],['طالبو خدمة',summary!.requesterUsers],['موردون',summary!.supplierUsers],['إجمالي الطلبات',summary!.totalRequests],['طلبات جديدة',summary!.newRequests],['Open',summary!.openRequests],['In Progress',summary!.inProgressRequests],['Completed',summary!.completedRequests],['Cancelled',summary!.cancelledRequests],['Supplier Selected',summary!.supplierSelectedRequests],['إجمالي العروض',summary!.totalOffers],['عروض جديدة',summary!.newOffers],['متوسط العروض/طلب',summary!.averageOffersPerRequest.toFixed(2)],['طلبات بعرض',summary!.requestsWithOffers],['إجمالي الموردين',summary!.totalSuppliers],['موردون جدد',summary!.newSuppliers],['موثقون',summary!.verifiedSuppliers],['غير موثقين',summary!.unverifiedSuppliers],['PRO فعال',summary!.activeProSuppliers]].map(([l,v])=><Stat key={String(l)} label={String(l)} value={String(v)}/>)}</div></Section>
 <Section title="Request Funnel"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['Requests Created',funnel!.requestsCreated,funnel!.requestsCreated],['Requests With Offers',funnel!.requestsWithOffers,funnel!.offersRate],['Requests With Selected Supplier',funnel!.requestsWithSelectedSupplier,funnel!.selectionRate],['Requests Started',funnel!.requestsStarted,funnel!.startRate],['Requests Completed',funnel!.requestsCompleted,funnel!.completionRate]].map(([l,v,r])=><div key={String(l)} className="rounded-2xl border border-slate-200 p-4"><p className="text-xs font-black text-slate-400">{l}</p><p className="mt-2 text-2xl font-black">{nf.format(Number(v))}</p>{r!==null&&typeof r==='number'&&l!=='Requests Created'&&<p className="mt-1 text-xs font-bold text-slate-500">{r}% من الطلبات المنشأة</p>}</div>)}</div></Section>
 <Section title="Offers Analytics"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Stat label="متوسط العروض لكل طلب" value={offers!.averageOffersPerRequest.toFixed(2)}/><Stat label="أعلى عدد عروض" value={offers!.maxOffersOnRequest}/><Stat label="طلبات بلا عروض" value={offers!.requestsWithoutOffers}/><Stat label="طلب بعرض واحد" value={offers!.requestsWithOneOffer}/><Stat label="طلبات بأكثر من عرض" value={offers!.requestsWithMoreThanOneOffer}/></div></Section>
 <Section title="Top Categories"><SimpleTable headers={['التصنيف','الطلبات','العروض','الموردون']} rows={cats.map(x=>[x.name,x.requestCount,x.offerCount,x.supplierCount])}/><Pager page={catPage} next={catNext} onPage={setCatPage}/></Section>
 <Section title="Top Cities"><SimpleTable headers={['المدينة','الطلبات','الموردون','الطلبات المكتملة']} rows={cities.map(x=>[x.name,x.requestCount,x.supplierCount,x.completedRequestCount])}/><Pager page={cityPage} next={cityNext} onPage={setCityPage}/></Section>
 <Section title="Most Active Suppliers"><SimpleTable headers={['المورد','العروض','المختارة','المكتملة','التقييم','Verified','PRO']} rows={suppliers.map(x=>[x.supplierName,x.offerCount,x.selectedOfferCount,x.completedRequestCount,x.ratingAverage==null?'—':x.ratingAverage.toFixed(2),x.verified?'نعم':'لا',x.isPro?'نعم':'لا'])}/><Pager page={supplierPage} next={supplierNext} onPage={setSupplierPage}/></Section>
 <Section title="Activity Over Time"><div className="space-y-3">{activity.map(x=><div key={x.bucket} className="grid grid-cols-[100px_1fr] gap-3 items-center"><span className="text-xs font-bold text-slate-500">{new Date(x.bucket).toLocaleDateString('ar-SY',{year:'numeric',month:granularity==='month'?'long':'2-digit',day:granularity==='day'?'2-digit':undefined})}</span><div className="space-y-1"><Bar label="طلبات" value={x.requestCount}/><Bar label="عروض" value={x.offerCount}/><Bar label="مستخدمون" value={x.newUserCount}/></div></div>)}</div></Section>
 <Section title="Request Status Distribution"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{statuses.map(x=><div key={x.status} className="rounded-2xl border border-slate-200 p-4"><div className="flex justify-between font-black"><span>{statusLabel(x.status)}</span><span>{nf.format(x.requestCount)}</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-slate-900" style={{width:`${Math.min(100,(x.requestCount/Math.max(1,Math.max(...statuses.map((s: StatusPoint)=>s.requestCount))))*100)}%`}}/></div></div>)}</div></Section>
 <Section title="PRO Analytics"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Stat label="PRO نشط" value={pro!.activePro}/><Stat label="طلبات PRO الحالية (معلقة)" value={pro!.pendingPro}/><Stat label="PRO منتهٍ" value={pro!.expiredPro}/><Stat label="انتهت خلال الفترة" value={pro!.expiredDuringPeriod}/><Stat label="طلبات تفعيل خلال الفترة" value={pro!.proActivationsDuringPeriod}/></div></Section>
 <Section title="Verification Analytics"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Stat label="Pending" value={verification!.pending}/><Stat label="Approved" value={verification!.approved}/><Stat label="Rejected" value={verification!.rejected}/><Stat label="Cancelled" value={verification!.cancelled}/><Stat label="طلبات توثيق خلال الفترة" value={verification!.createdDuringPeriod}/></div></Section>
 </>}
 </AdminPage>
}
function Section({title,children}:{title:string;children:ReactNode}){return <section className="mb-7"><h2 className="mb-4 text-xl font-black">{title}</h2>{children}</section>}
function Stat({label,value}:{label:string,value:string|number}){return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs font-black text-slate-400">{label}</p><p className="mt-2 text-2xl font-black">{typeof value==='number'?nf.format(value):value}</p></div>}
function SimpleTable({headers,rows}:{headers:string[];rows:(string|number)[][]}){return <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full min-w-[620px] text-right text-sm"><thead className="bg-slate-50"><tr>{headers.map(h=><th key={h} className="px-4 py-3 font-black">{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i} className="border-t border-slate-100">{r.map((c,j)=><td key={j} className="px-4 py-3 font-bold">{typeof c==='number'?nf.format(c):c}</td>)}</tr>):<tr><td colSpan={headers.length} className="px-4 py-8 text-center font-bold text-slate-500">لا توجد بيانات ضمن الفترة المحددة.</td></tr>}</tbody></table></div>}
function Pager({page,next,onPage}:{page:number;next:boolean;onPage:(p:number)=>void}){return <div className="mt-3 flex justify-center gap-2"><button disabled={page<=1} onClick={()=>onPage(page-1)} className="rounded-lg border px-3 py-1.5 text-xs font-bold disabled:opacity-40">السابق</button><span className="px-3 py-1.5 text-xs font-black">صفحة {page}</span><button disabled={!next} onClick={()=>onPage(page+1)} className="rounded-lg border px-3 py-1.5 text-xs font-bold disabled:opacity-40">التالي</button></div>}
function Bar({label,value}:{label:string,value:number}){return <div className="flex items-center gap-2 text-[10px] font-bold"><span className="w-12">{label}</span><div className="h-2 flex-1 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-slate-800" style={{width:`${Math.min(100,value===0?0:Math.max(4,value/10))}%`}}/></div><span className="w-10 text-left">{nf.format(value)}</span></div>}
function statusLabel(s:string){return ({open:'Open',supplier_selected:'Supplier Selected',in_progress:'In Progress',completed:'Completed',cancelled:'Cancelled',closed:'Closed'} as Record<string,string>)[s]??s}
function Loading(){return <div className="space-y-6">{Array.from({length:7}).map((_,i)=><div key={i} className="h-36 animate-pulse rounded-2xl bg-slate-200"/>)}</div>}
