import { useEffect, useState } from "react";
import AdminRoute from "../components/AdminRoute";
import { getAdminUsers, setAdminUserActive } from "../services/adminService";
import { AdminPage } from "./AdminDashboardPage";

export default function AdminUsersPage(){ return <AdminRoute><Content/></AdminRoute>; }
function Content(){ const [search,setSearch]=useState(""); const [role,setRole]=useState<""|"requester"|"supplier">(""); const [verified,setVerified]=useState(""); const [page,setPage]=useState(1); const [state,setState]=useState<Awaited<ReturnType<typeof getAdminUsers>> | null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  async function load(){setLoading(true);setError("");const r=await getAdminUsers({search,role:role||undefined,verified:verified===""?undefined:verified==="true",page,pageSize:12});setState(r);if(r.error)setError("تعذر تحميل المستخدمين.");setLoading(false)}
  useEffect(()=>{const t=window.setTimeout(()=>void load(),250);return()=>window.clearTimeout(t)},[search,role,verified,page]);
  return <AdminPage><Header title="المستخدمون" back="/admin"/><div className="mb-5 grid gap-3 md:grid-cols-[1fr_180px_180px]"><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="بحث بالاسم" className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-slate-400"/><select value={role} onChange={e=>{setRole(e.target.value as typeof role);setPage(1)}} className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm"><option value="">كل الأدوار</option><option value="requester">Requester</option><option value="supplier">Supplier</option></select><select value={verified} onChange={e=>{setVerified(e.target.value);setPage(1)}} className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm"><option value="">كل حالات التوثيق</option><option value="true">موثق</option><option value="false">غير موثق</option></select></div>{error&&<Alert text={error}/>} {loading?<Loading/>:state?.users.length? <><div className="grid gap-3">{state.users.map(u=><article key={u.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-black">{u.fullName||"مستخدم بدون اسم"}</h3><p className="mt-1 text-sm text-slate-500">{u.role==='supplier'?'مورد':'صاحب طلب'} · انضم {date(u.createdAt)}</p></div><div className="flex flex-wrap gap-2 text-xs font-black"><span className="rounded-full bg-slate-100 px-3 py-1">{u.role}</span><span className={u.isActive?"rounded-full bg-emerald-50 px-3 py-1 text-emerald-700":"rounded-full bg-rose-50 px-3 py-1 text-rose-700"}>{u.isActive?"نشط":"موقوف"}</span>{u.role==='supplier'&&<span className={u.verified?'rounded-full bg-emerald-50 px-3 py-1 text-emerald-700':'rounded-full bg-slate-100 px-3 py-1 text-slate-600'}>{u.verified?'موثق':'غير موثق'}</span>}{u.role==='supplier'&&<span className="rounded-full bg-blue-50 px-3 py-1 text-blue-700">{pro(u.proStatus)}</span>}</div><button type="button" onClick={async()=>{const next=!u.isActive;if(!window.confirm(next?"إعادة تفعيل هذا الحساب؟":"إيقاف هذا الحساب؟")) return; const r=await setAdminUserActive(u.id,next); if(r.error) window.alert(r.error.message); else void load();}} className={`rounded-xl px-4 py-2.5 text-sm font-black ${u.isActive?"border border-rose-200 bg-rose-50 text-rose-700":"bg-emerald-600 text-white"}`}>{u.isActive?"إيقاف الحساب":"إعادة التفعيل"}</button></div></article>)}</div><Pager page={page} hasNext={state.hasNextPage} total={state.totalCount} onPrev={()=>setPage(p=>Math.max(1,p-1))} onNext={()=>setPage(p=>p+1)}/></>:<Empty text="لا يوجد مستخدمون مطابقون."/>}</AdminPage> }
const pro=(s:string|null)=>({active:"PRO فعّال",pending:"PRO معلّق",expired:"PRO منتهي",cancelled:"PRO ملغى",free:"FREE"}[s||"free"]||"—"); const date=(v:string)=>new Date(v).toLocaleDateString("ar-SY");
function Header({title,back}:{title:string;back:string}){return <div className="mb-7 flex items-center justify-between"><div><p className="text-sm font-black text-slate-400">إدارة المنصة</p><h1 className="mt-1 text-3xl font-black">{title}</h1></div><a href={back} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold">لوحة الإدارة</a></div>}; function Pager(p:{page:number;hasNext:boolean;total:number;onPrev:()=>void;onNext:()=>void}){return <div className="mt-5 flex items-center justify-between rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm"><span className="font-bold text-slate-500">إجمالي النتائج: {p.total}</span><div className="flex gap-2"><button disabled={p.page===1} onClick={p.onPrev} className="rounded-lg border px-3 py-2 disabled:opacity-40">السابق</button><span className="px-2 py-2 font-black">{p.page}</span><button disabled={!p.hasNext} onClick={p.onNext} className="rounded-lg border px-3 py-2 disabled:opacity-40">التالي</button></div></div>}; function Loading(){return <div className="rounded-2xl bg-white p-10 text-center font-bold">جارٍ التحميل...</div>}; function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center font-bold text-slate-500">{text}</div>}; function Alert({text}:{text:string}){return <div className="mb-4 rounded-xl bg-rose-50 px-4 py-3 text-sm font-bold text-rose-700">{text}</div>}
