import { useEffect, useState, type ReactNode } from "react";
import AdminRoute from "../components/AdminRoute";
import DashboardStatCard from "../components/DashboardStatCard";
import { getAdminStats } from "../services/adminService";
import { getAdminSupportSummary } from "../services/supportService";

export default function AdminDashboardPage() { return <AdminRoute><AdminDashboardContent /></AdminRoute>; }

function AdminDashboardContent() {
  const [stats, setStats] = useState<Awaited<ReturnType<typeof getAdminStats>>["stats"]>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [support, setSupport] = useState<Awaited<ReturnType<typeof getAdminSupportSummary>>["summary"]>(null);
  async function load() { setLoading(true); setError(""); const [result,supportResult] = await Promise.all([getAdminStats(),getAdminSupportSummary()]); setStats(result.stats); setSupport(supportResult.summary); if (result.error || supportResult.error) setError("تعذر تحميل بعض إحصائيات الإدارة."); setLoading(false); }
  useEffect(() => { void load(); }, []);
  return <AdminPage>
    <div className="mb-8 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-black text-slate-400">إدارة المنصة</p><h1 className="mt-1 text-3xl font-black tracking-tight">لوحة إدارة MATLOOB</h1><p className="mt-2 text-sm text-slate-500">نظرة عامة على المستخدمين والطلبات والموردين والخدمات الإدارية.</p></div><button onClick={() => void load()} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold hover:bg-slate-50">تحديث البيانات</button></div>
    {error && <div className="mb-6 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-bold text-rose-700">{error}</div>}
    {loading ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Array.from({length:8}).map((_,i)=><div key={i} className="h-32 animate-pulse rounded-2xl bg-slate-200" />)}</div> : stats && <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
      <DashboardStatCard label="إجمالي المستخدمين" value={stats.totalUsers} /><DashboardStatCard label="أصحاب الطلبات" value={stats.requesterUsers} /><DashboardStatCard label="الموردون" value={stats.supplierUsers} /><DashboardStatCard label="إجمالي الطلبات" value={stats.totalRequests} /><DashboardStatCard label="الطلبات المفتوحة" value={stats.openRequests} /><DashboardStatCard label="الطلبات المكتملة" value={stats.completedRequests} /><DashboardStatCard label="إجمالي العروض" value={stats.totalOffers} /><DashboardStatCard label="الموردون الموثقون" value={stats.verifiedSuppliers} /><DashboardStatCard label="PRO النشط" value={stats.activeProSubscriptions} /><DashboardStatCard label="طلبات التوثيق المعلقة" value={stats.pendingVerificationRequests} /><DashboardStatCard label="طلبات PRO المعلقة" value={stats.pendingProSubscriptions} /><DashboardStatCard label="تذاكر مفتوحة" value={support?.open_tickets ?? 0} /><DashboardStatCard label="تذاكر قيد المعالجة" value={support?.in_progress_tickets ?? 0} /><DashboardStatCard label="تذاكر بانتظار المستخدم" value={support?.waiting_user_tickets ?? 0} /><DashboardStatCard label="تذاكر عاجلة" value={support?.urgent_tickets ?? 0} />
    </div>}
    <section className="mt-8"><h2 className="mb-4 text-xl font-black">الوصول السريع</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Quick href="/admin/reports" title="التقارير والإحصائيات" text="تحليل أداء المنصة" /><Quick href="/admin/users" title="المستخدمون" text="عرض وبحث المستخدمين" /><Quick href="/admin/requests" title="الطلبات" text="بحث ومراجعة الطلبات" /><Quick href="/admin/suppliers" title="الموردون" text="إدارة دليل الموردين" /><Quick href="/admin/categories" title="التصنيفات" text="إدارة التصنيفات" /><Quick href="/admin/cities" title="المدن" text="إدارة المدن" /><Quick href="/admin/verification" title="طلبات التوثيق" text="مراجعة طلبات التوثيق" badge={stats?.pendingVerificationRequests} /><Quick href="/admin/support" title="الدعم" text="إدارة تذاكر الدعم" badge={support?.open_tickets} /><Quick href="/admin/pro" title="إدارة PRO" text="إدارة اشتراكات PRO" badge={stats?.pendingProSubscriptions} /></div></section>
  </AdminPage>;
}
function Quick({href,title,text,badge}:{href:string;title:string;text:string;badge?:number}) { return <a href={href} className="relative rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-slate-300"><h3 className="font-black">{title}</h3><p className="mt-2 text-sm text-slate-500">{text}</p>{badge !== undefined && <span className="absolute left-4 top-4 rounded-full bg-amber-50 px-2.5 py-1 text-xs font-black text-amber-700">{badge}</span>}</a>; }
export function AdminPage({children}:{children:ReactNode}) { return <main dir="rtl" className="min-h-screen bg-slate-50 px-4 py-8 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><nav className="mb-7 flex gap-2 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-2 shadow-sm"><a href="/admin" className="shrink-0 rounded-xl px-3 py-2 text-sm font-bold hover:bg-slate-50">الرئيسية</a><a href="/admin/reports" className="shrink-0 rounded-xl px-3 py-2 text-sm font-bold hover:bg-slate-50">التقارير</a><a href="/admin/users" className="shrink-0 rounded-xl px-3 py-2 text-sm font-bold hover:bg-slate-50">المستخدمون</a><a href="/admin/requests" className="shrink-0 rounded-xl px-3 py-2 text-sm font-bold hover:bg-slate-50">الطلبات</a><a href="/admin/suppliers" className="shrink-0 rounded-xl px-3 py-2 text-sm font-bold hover:bg-slate-50">الموردون</a><a href="/admin/categories" className="shrink-0 rounded-xl px-3 py-2 text-sm font-bold hover:bg-slate-50">التصنيفات</a><a href="/admin/cities" className="shrink-0 rounded-xl px-3 py-2 text-sm font-bold hover:bg-slate-50">المدن</a><a href="/admin/verification" className="shrink-0 rounded-xl px-3 py-2 text-sm font-bold hover:bg-slate-50">التوثيق</a><a href="/admin/support" className="shrink-0 rounded-xl px-3 py-2 text-sm font-bold hover:bg-slate-50">الدعم</a><a href="/admin/pro" className="shrink-0 rounded-xl px-3 py-2 text-sm font-bold hover:bg-slate-50">PRO</a></nav>{children}</div></main>; }
