import { useEffect, useState, type FormEvent } from 'react';
import ProtectedRoute from '../components/ProtectedRoute';
import { createSupportTicket, getMySupportTickets } from '../services/supportService';
import type { SupportCategory, SupportTicket } from '../types/support';

const categories:[SupportCategory,string][]=[['account','الحساب'],['request','الطلبات'],['offer','العروض'],['supplier','الموردون'],['verification','التوثيق'],['subscription','PRO / الاشتراك'],['technical','مشكلة تقنية'],['other','أخرى']];
const statusLabel=(s:string)=>({open:'مفتوحة',in_progress:'قيد المعالجة',waiting_user:'بانتظار ردك',resolved:'تم الحل',closed:'مغلقة'} as Record<string,string>)[s]||s;
const priorityLabel=(p:string)=>({low:'منخفضة',normal:'عادية',high:'عالية',urgent:'عاجلة'} as Record<string,string>)[p]||p;
const date=(v:string)=>new Intl.DateTimeFormat('ar-SY',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v));

export default function SupportPage(){return <ProtectedRoute><SupportContent/></ProtectedRoute>}
function SupportContent(){
 const [tickets,setTickets]=useState<SupportTicket[]>([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[success,setSuccess]=useState('');
 const [subject,setSubject]=useState(''),[category,setCategory]=useState<SupportCategory>('technical'),[message,setMessage]=useState(''),[sending,setSending]=useState(false);
 const load=async(p=page)=>{setLoading(true);setError('');const r=await getMySupportTickets(p,12);setTickets(r.tickets);setTotal(r.totalCount);if(r.error)setError('تعذر تحميل تذاكر الدعم.');setLoading(false)};
 useEffect(()=>{void load(1)},[]);
 const submit=async(e:FormEvent)=>{e.preventDefault();if(sending)return;setSending(true);setError('');setSuccess('');const r=await createSupportTicket(subject,category,message);if(r.error){setError(r.error.message||'تعذر إنشاء التذكرة.')}else{setSubject('');setMessage('');setSuccess('تم إنشاء تذكرة الدعم.');if(r.ticket)window.location.href=`/support/${r.ticket.id}`;else void load(1)}setSending(false)};
 return <main dir="rtl" className="min-h-screen bg-slate-50 px-4 py-10 text-slate-950"><div className="mx-auto max-w-6xl"><div className="mb-8"><p className="text-sm font-black text-slate-400">مركز المساعدة</p><h1 className="mt-2 text-3xl font-black">الدعم</h1><p className="mt-2 text-sm text-slate-500">أنشئ تذكرة وتابع المحادثة مع فريق الدعم من داخل مطلوب.</p></div>
 <div className="grid gap-6 lg:grid-cols-[1fr_1.35fr]">
 <form onSubmit={submit} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">إنشاء تذكرة دعم</h2><label className="mt-6 block text-sm font-black">الموضوع<input required maxLength={200} value={subject} onChange={e=>setSubject(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-slate-400"/></label><label className="mt-4 block text-sm font-black">التصنيف<select value={category} onChange={e=>setCategory(e.target.value as SupportCategory)} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3">{categories.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="mt-4 block text-sm font-black">الرسالة<textarea required maxLength={5000} value={message} onChange={e=>setMessage(e.target.value)} rows={7} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-slate-400"/><span className="mt-1 block text-xs font-bold text-slate-400">{message.length}/5000</span></label>{error&&<div className="mt-4 rounded-xl bg-rose-50 px-4 py-3 text-sm font-bold text-rose-700">{error}</div>}{success&&<div className="mt-4 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-700">{success}</div>}<button disabled={sending} className="mt-5 w-full rounded-xl bg-slate-950 px-5 py-3.5 font-black text-white disabled:cursor-not-allowed disabled:opacity-50">{sending?'جارٍ الإرسال...':'إرسال التذكرة'}</button></form>
 <section><div className="mb-4 flex items-end justify-between"><div><h2 className="text-xl font-black">تذاكري</h2><p className="mt-1 text-sm text-slate-500">التذاكر المرتبطة بحسابك فقط.</p></div><button onClick={()=>void load(page)} className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-bold">تحديث</button></div>{loading?<div className="rounded-3xl bg-white p-12 text-center font-bold text-slate-500">جارٍ التحميل...</div>:tickets.length===0?<div className="rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center"><h3 className="font-black">لا توجد تذاكر بعد</h3><p className="mt-2 text-sm text-slate-500">أنشئ أول تذكرة من النموذج.</p></div>:<div className="space-y-3">{tickets.map(t=><a key={t.id} href={`/support/${t.id}`} className="block rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:border-slate-300"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-black">{t.subject}</h3><p className="mt-2 text-xs font-bold text-slate-400">{categories.find(c=>c[0]===t.category)?.[1]||t.category} · {date(t.created_at)}</p></div><div className="flex gap-2"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-black">{statusLabel(t.status)}</span><span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-black text-amber-700">{priorityLabel(t.priority)}</span></div></div><p className="mt-3 text-xs font-bold text-slate-400">آخر تحديث: {date(t.updated_at)} ←</p></a>)}</div>}{total>12&&<div className="mt-5 flex items-center justify-between rounded-xl bg-white p-3"><button disabled={page===1} onClick={()=>{setPage(p=>p-1);void load(page-1)}} className="rounded-lg border px-3 py-2 text-sm font-bold disabled:opacity-40">السابق</button><span className="text-sm font-black">صفحة {page} / {Math.ceil(total/12)}</span><button disabled={page>=Math.ceil(total/12)} onClick={()=>{setPage(p=>p+1);void load(page+1)}} className="rounded-lg border px-3 py-2 text-sm font-bold disabled:opacity-40">التالي</button></div>}</section></div></div></main>
}
